
#Server Settings
[server]
#Disable / enable any items here (disables their recipes)
enabledItems = [
	"sophisticatedbackpacks:backpack|false",
	"sophisticatedbackpacks:iron_backpack|false",
	"sophisticatedbackpacks:gold_backpack|false",
	"sophisticatedbackpacks:diamond_backpack|false",
	"sophisticatedbackpacks:netherite_backpack|false",
	"sophisticatedbackpacks:pickup_upgrade|false",
	"sophisticatedbackpacks:advanced_pickup_upgrade|false",
	"sophisticatedbackpacks:filter_upgrade|false",
	"sophisticatedbackpacks:advanced_filter_upgrade|false",
	"sophisticatedbackpacks:magnet_upgrade|false",
	"sophisticatedbackpacks:advanced_magnet_upgrade|false",
	"sophisticatedbackpacks:feeding_upgrade|false",
	"sophisticatedbackpacks:advanced_feeding_upgrade|false",
	"sophisticatedbackpacks:compacting_upgrade|false",
	"sophisticatedbackpacks:advanced_compacting_upgrade|false",
	"sophisticatedbackpacks:void_upgrade|false",
	"sophisticatedbackpacks:advanced_void_upgrade|false",
	"sophisticatedbackpacks:restock_upgrade|false",
	"sophisticatedbackpacks:advanced_restock_upgrade|false",
	"sophisticatedbackpacks:deposit_upgrade|false",
	"sophisticatedbackpacks:advanced_deposit_upgrade|false",
	"sophisticatedbackpacks:refill_upgrade|false",
	"sophisticatedbackpacks:advanced_refill_upgrade|false",
	"sophisticatedbackpacks:inception_upgrade|false",
	"sophisticatedbackpacks:everlasting_upgrade|false",
	"sophisticatedbackpacks:smelting_upgrade|false",
	"sophisticatedbackpacks:auto_smelting_upgrade|false",
	"sophisticatedbackpacks:smoking_upgrade|false",
	"sophisticatedbackpacks:auto_smoking_upgrade|false",
	"sophisticatedbackpacks:blasting_upgrade|false",
	"sophisticatedbackpacks:auto_blasting_upgrade|false",
	"sophisticatedbackpacks:crafting_upgrade|false",
	"sophisticatedbackpacks:stonecutter_upgrade|false",
	"sophisticatedbackpacks:stack_upgrade_tier_1|false",
	"sophisticatedbackpacks:stack_upgrade_tier_2|false",
	"sophisticatedbackpacks:stack_upgrade_tier_3|false",
	"sophisticatedbackpacks:stack_upgrade_tier_4|false",
	"sophisticatedbackpacks:jukebox_upgrade|false",
	"sophisticatedbackpacks:tool_swapper_upgrade|false",
	"sophisticatedbackpacks:advanced_tool_swapper_upgrade|false",
	"sophisticatedbackpacks:tank_upgrade|false",
	"sophisticatedbackpacks:battery_upgrade|false",
	"sophisticatedbackpacks:pump_upgrade|false",
	"sophisticatedbackpacks:advanced_pump_upgrade|false",
	"sophisticatedbackpacks:xp_pump_upgrade|false",
	"sophisticatedbackpacks:upgrade_base|false",
	"sophisticatedstorage:barrel|false",
	"sophisticatedstorage:iron_barrel|false",
	"sophisticatedstorage:gold_barrel|false",
	"sophisticatedstorage:diamond_barrel|false",
	"sophisticatedstorage:netherite_barrel|false",
	"sophisticatedstorage:limited_barrel_1|false",
	"sophisticatedstorage:limited_iron_barrel_1|false",
	"sophisticatedstorage:limited_gold_barrel_1|false",
	"sophisticatedstorage:limited_diamond_barrel_1|false",
	"sophisticatedstorage:limited_netherite_barrel_1|false",
	"sophisticatedstorage:limited_barrel_2|false",
	"sophisticatedstorage:limited_iron_barrel_2|false",
	"sophisticatedstorage:limited_gold_barrel_2|false",
	"sophisticatedstorage:limited_diamond_barrel_2|false",
	"sophisticatedstorage:limited_netherite_barrel_2|false",
	"sophisticatedstorage:limited_barrel_3|false",
	"sophisticatedstorage:limited_iron_barrel_3|false",
	"sophisticatedstorage:limited_gold_barrel_3|false",
	"sophisticatedstorage:limited_diamond_barrel_3|false",
	"sophisticatedstorage:limited_netherite_barrel_3|false",
	"sophisticatedstorage:limited_barrel_4|false",
	"sophisticatedstorage:limited_iron_barrel_4|false",
	"sophisticatedstorage:limited_gold_barrel_4|false",
	"sophisticatedstorage:limited_diamond_barrel_4|false",
	"sophisticatedstorage:limited_netherite_barrel_4|false",
	"sophisticatedstorage:chest|false",
	"sophisticatedstorage:iron_chest|false",
	"sophisticatedstorage:gold_chest|false",
	"sophisticatedstorage:diamond_chest|false",
	"sophisticatedstorage:netherite_chest|false",
	"sophisticatedstorage:shulker_box|false",
	"sophisticatedstorage:iron_shulker_box|false",
	"sophisticatedstorage:gold_shulker_box|false",
	"sophisticatedstorage:diamond_shulker_box|false",
	"sophisticatedstorage:netherite_shulker_box|false",
	"sophisticatedstorage:controller|false",
	"sophisticatedstorage:storage_link|false",
	"sophisticatedstorage:pickup_upgrade|false",
	"sophisticatedstorage:advanced_pickup_upgrade|false",
	"sophisticatedstorage:filter_upgrade|false",
	"sophisticatedstorage:advanced_filter_upgrade|false",
	"sophisticatedstorage:magnet_upgrade|false",
	"sophisticatedstorage:advanced_magnet_upgrade|false",
	"sophisticatedstorage:feeding_upgrade|false",
	"sophisticatedstorage:advanced_feeding_upgrade|false",
	"sophisticatedstorage:compacting_upgrade|false",
	"sophisticatedstorage:advanced_compacting_upgrade|false",
	"sophisticatedstorage:void_upgrade|false",
	"sophisticatedstorage:advanced_void_upgrade|false",
	"sophisticatedstorage:smelting_upgrade|false",
	"sophisticatedstorage:auto_smelting_upgrade|false",
	"sophisticatedstorage:smoking_upgrade|false",
	"sophisticatedstorage:auto_smoking_upgrade|false",
	"sophisticatedstorage:blasting_upgrade|false",
	"sophisticatedstorage:auto_blasting_upgrade|false",
	"sophisticatedstorage:crafting_upgrade|false",
	"sophisticatedstorage:stonecutter_upgrade|false",
	"sophisticatedstorage:stack_upgrade_tier_1|false",
	"sophisticatedstorage:stack_upgrade_tier_2|false",
	"sophisticatedstorage:stack_upgrade_tier_3|false",
	"sophisticatedstorage:stack_upgrade_tier_4|false",
	"sophisticatedstorage:jukebox_upgrade|false",
	"sophisticatedstorage:pump_upgrade|false",
	"sophisticatedstorage:advanced_pump_upgrade|false",
	"sophisticatedstorage:xp_pump_upgrade|false",
	"sophisticatedstorage:compression_upgrade|false",
	"sophisticatedstorage:hopper_upgrade|false",
	"sophisticatedstorage:advanced_hopper_upgrade|false",
	"sophisticatedstorage:basic_tier_upgrade|false",
	"sophisticatedstorage:basic_to_iron_tier_upgrade|false",
	"sophisticatedstorage:iron_to_gold_tier_upgrade|false",
	"sophisticatedstorage:gold_to_diamond_tier_upgrade|false",
	"sophisticatedstorage:diamond_to_netherite_tier_upgrade|false",
	"sophisticatedstorage:upgrade_base|false",
	"sophisticatedstorage:packing_tape|false",
	"sophisticatedstorage:storage_tool|false",
	"sophisticatedstorage:debug_tool|false",
	"sophisticatedstorage:basic_to_gold_tier_upgrade|false",
	"sophisticatedstorage:basic_to_diamond_tier_upgrade|false",
	"sophisticatedstorage:basic_to_netherite_tier_upgrade|false",
	"sophisticatedstorage:iron_to_diamond_tier_upgrade|false",
	"sophisticatedstorage:iron_to_netherite_tier_upgrade|false",
	"sophisticatedstorage:gold_to_netherite_tier_upgrade|false",
]
