
[types]

	[types.wood_type]

		[types.wood_type.quark]
			bamboo = true
			azalea = false
			blossom = false
			ancient = false

		[types.wood_type.create_dd]
			rose = false
			smoked = true
			spirit = true
			rubber = true

		[types.wood_type.ecologics]
			flowering_azalea = true
			azalea = true
			coconut = true
			walnut = true

	[types.leaves_type]

		[types.leaves_type.quark]
			blue_blossom = false
			lavender_blossom = false
			orange_blossom = false
			pink_blossom = false
			yellow_blossom = false
			red_blossom = false
			ancient = false

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.leaves_type.create_dd]
			rubber = false

	[types.cut_block_type]

		[types.cut_block_type.create_things_and_misc]
			brass_tiles = true
			brass_brick = true

		[types.cut_block_type.create_dd]
			rose = true
			smoked = true
			spirit = true
			cut_potassic = true
			polished_cut_potassic = true
			cut_potassic_brick = true
			small_potassic_brick = true
			cut_weathered_limestone = true
			polished_cut_weathered_limestone = true
			cut_weathered_limestone_brick = true
			small_weathered_limestone_brick = true
			cut_gabbro = true
			polished_cut_gabbro = true
			cut_gabbro_brick = true
			small_gabbro_brick = true
			rubber = false
			cut_aethersite = true
			polished_cut_aethersite = true
			cut_aethersite_brick = true
			small_aethersite_brick = true
			cut_dolomite = true
			polished_cut_dolomite = true
			cut_dolomite_brick = true
			small_dolomite_brick = true

		[types.cut_block_type.createindustry]
			concrete = true
			rebar_concrete = true
			factory_floor = false
			cut_bauxite = true
			polished_cut_bauxite = true
			cut_bauxite_brick = true
			small_bauxite_brick = true
			white_concrete = false
			light_gray_concrete = false
			gray_concrete = false
			black_concrete = false
			brown_concrete = false
			red_concrete = false
			orange_concrete = false
			yellow_concrete = false
			lime_concrete = false
			green_concrete = false
			purple_concrete = false
			cyan_concrete = false
			light_blue_concrete = false
			blue_concrete = false
			magenta_concrete = false
			pink_concrete = false

		[types.cut_block_type.create]
			copper_shingle = true
			exposed_copper_shingle = true
			weathered_copper_shingle = true
			oxidized_copper_shingle = true
			waxed_copper_shingle = true
			waxed_exposed_copper_shingle = true
			waxed_weathered_copper_shingle = true
			waxed_oxidized_copper_shingle = true
			copper_tile = true
			exposed_copper_tile = true
			weathered_copper_tile = true
			oxidized_copper_tile = true
			waxed_copper_tile = true
			waxed_exposed_copper_tile = true
			waxed_weathered_copper_tile = true
			waxed_oxidized_copper_tile = true
			cut_granite = true
			polished_cut_granite = true
			cut_granite_brick = true
			small_granite_brick = true
			cut_diorite = true
			polished_cut_diorite = true
			cut_diorite_brick = true
			small_diorite_brick = true
			cut_andesite = true
			polished_cut_andesite = true
			cut_andesite_brick = true
			small_andesite_brick = true
			cut_calcite = true
			polished_cut_calcite = true
			cut_calcite_brick = true
			small_calcite_brick = true
			cut_dripstone = true
			polished_cut_dripstone = true
			cut_dripstone_brick = true
			small_dripstone_brick = true
			cut_deepslate = true
			polished_cut_deepslate = true
			cut_deepslate_brick = true
			small_deepslate_brick = true
			cut_tuff = true
			polished_cut_tuff = true
			cut_tuff_brick = true
			small_tuff_brick = true
			cut_asurine = true
			polished_cut_asurine = true
			cut_asurine_brick = true
			small_asurine_brick = true
			cut_crimsite = true
			polished_cut_crimsite = true
			cut_crimsite_brick = true
			small_crimsite_brick = true
			cut_limestone = true
			polished_cut_limestone = true
			cut_limestone_brick = true
			small_limestone_brick = true
			cut_ochrum = true
			polished_cut_ochrum = true
			cut_ochrum_brick = true
			small_ochrum_brick = true
			cut_scoria = true
			polished_cut_scoria = true
			cut_scoria_brick = true
			small_scoria_brick = true
			cut_scorchia = true
			polished_cut_scorchia = true
			cut_scorchia_brick = true
			small_scorchia_brick = true
			cut_veridium = true
			polished_cut_veridium = true
			cut_veridium_brick = true
			small_veridium_brick = true

		[types.cut_block_type.createdeco]
			worn_bricks = true
			worn_brick_tiles = true
			worn_long_bricks = true
			worn_short_bricks = true
			cracked_worn_bricks = true
			cracked_worn_brick_tiles = true
			cracked_worn_long_bricks = true
			cracked_worn_short_bricks = true
			mossy_worn_bricks = true
			mossy_worn_brick_tiles = true
			mossy_worn_long_bricks = true
			mossy_worn_short_bricks = true
			pearl_bricks = true
			pearl_brick_tiles = true
			pearl_long_bricks = true
			pearl_short_bricks = true
			cracked_pearl_bricks = true
			cracked_pearl_brick_tiles = true
			cracked_pearl_long_bricks = true
			cracked_pearl_short_bricks = true
			mossy_pearl_bricks = true
			mossy_pearl_brick_tiles = true
			mossy_pearl_long_bricks = true
			mossy_pearl_short_bricks = true
			red_brick_tiles = true
			red_long_bricks = true
			red_short_bricks = true
			cracked_red_bricks = true
			cracked_red_brick_tiles = true
			cracked_red_long_bricks = true
			cracked_red_short_bricks = true
			mossy_red_bricks = true
			mossy_red_brick_tiles = true
			mossy_red_long_bricks = true
			mossy_red_short_bricks = true
			blue_bricks = true
			blue_brick_tiles = true
			blue_long_bricks = true
			blue_short_bricks = true
			cracked_blue_bricks = true
			cracked_blue_brick_tiles = true
			cracked_blue_long_bricks = true
			cracked_blue_short_bricks = true
			mossy_blue_bricks = true
			mossy_blue_brick_tiles = true
			mossy_blue_long_bricks = true
			mossy_blue_short_bricks = true
			dusk_bricks = true
			dusk_brick_tiles = true
			dusk_long_bricks = true
			dusk_short_bricks = true
			cracked_dusk_bricks = true
			cracked_dusk_brick_tiles = true
			cracked_dusk_long_bricks = true
			cracked_dusk_short_bricks = true
			mossy_dusk_bricks = true
			mossy_dusk_brick_tiles = true
			mossy_dusk_long_bricks = true
			mossy_dusk_short_bricks = true
			dean_bricks = true
			dean_brick_tiles = true
			dean_long_bricks = true
			dean_short_bricks = true
			cracked_dean_bricks = true
			cracked_dean_brick_tiles = true
			cracked_dean_long_bricks = true
			cracked_dean_short_bricks = true
			mossy_dean_bricks = true
			mossy_dean_brick_tiles = true
			mossy_dean_long_bricks = true
			mossy_dean_short_bricks = true
			scarlet_bricks = true
			scarlet_brick_tiles = true
			scarlet_long_bricks = true
			scarlet_short_bricks = true
			cracked_scarlet_bricks = true
			cracked_scarlet_brick_tiles = true
			cracked_scarlet_long_bricks = true
			cracked_scarlet_short_bricks = true
			mossy_scarlet_bricks = true
			mossy_scarlet_brick_tiles = true
			mossy_scarlet_long_bricks = true
			mossy_scarlet_short_bricks = true

		[types.cut_block_type.ecologics]
			coconut = true
			seashell_tile = true
			ice_brick = true
			snow_brick = true
			walnut = true
			azalea = true
			flowering_azalea = true

		[types.cut_block_type.quark]
			ancient_planks = false
			limestone = true
			polished_limestone = true
			jasper = false
			polished_jasper = false
			shale = false
			polished_shale = false
			myalite = false
			polished_myalite = false
			blossom_planks = false
			permafrost = false
			permafrost_bricks = false
			azalea_planks = false
			soul_sandstone = true
			cut_soul_sandstone = true
			smooth_soul_sandstone = true
			thatch = true
			raw_iron_bricks = true
			raw_gold_bricks = true
			raw_copper_bricks = true
			blue_nether_bricks = true
			sandstone_bricks = true
			red_sandstone_bricks = true
			soul_sandstone_bricks = true
			cobblestone_bricks = true
			mossy_cobblestone_bricks = true
			blackstone_bricks = true
			dirt_bricks = true
			netherrack_bricks = true
			bamboo_planks = true
			calcite = true
			polished_calcite = true
			dripstone_block = true
			polished_dripstone = true
			tuff = true
			polished_tuff = true
			granite_bricks = true
			diorite_bricks = true
			andesite_bricks = true
			calcite_bricks = true
			dripstone_bricks = true
			tuff_bricks = true
			limestone_bricks = true
			jasper_bricks = false
			shale_bricks = false
			myalite_bricks = false
			midori_block = false
			duskbound_block = false
			iron_plate = true
			rusty_iron_plate = true
			shingles = false
			white_shingles = false
			orange_shingles = false
			magenta_shingles = false
			light_blue_shingles = false
			yellow_shingles = false
			lime_shingles = false
			pink_shingles = false
			gray_shingles = false
			light_gray_shingles = false
			cyan_shingles = false
			purple_shingles = false
			blue_shingles = false
			brown_shingles = false
			green_shingles = false
			red_shingles = false
			black_shingles = false

		[types.cut_block_type.supplementaries]
			lapis_bricks = true
			ash_bricks = true
			stone_tile = true
			blackstone_tile = true

		[types.cut_block_type.kubejs]
			waterproof = true

[entries]

	[entries.wood_type]

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			hollow_log = false

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.storagedrawers]
			full_drawers_2 = true
			half_drawers_1 = false
			full_drawers_4 = true
			half_drawers_4 = false
			trim = false
			half_drawers_2 = false
			full_drawers_1 = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

