
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.leaves_type]

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.leaves_type.northstar]
			coiler = true
			argyre = true
			wilter = true

	[types.cake]

		[types.cake.createaddition]
			chocolate_cake = true
			honey_cake = true

	[types.wood_type]

		[types.wood_type.ecologics]
			flowering_azalea = true
			azalea = true
			coconut = true
			walnut = true

		[types.wood_type.northstar]
			coiler = false
			wilter = false
			argyre = false
			calorian = false

	[types.stone_type]

		[types.stone_type.supplementaries]
			ash = true

		[types.stone_type.copperandtuffbackport]
			chiseled_tuff = true

		[types.stone_type.northstar]
			mars_stone = true
			moon_stone = true
			venus_stone = true
			mercury_stone = true

		[types.stone_type.create]
			cut_granite = true
			cut_diorite = true
			cut_andesite = true
			cut_calcite = true
			cut_dripstone = true
			cut_deepslate = true
			cut_tuff = true
			cut_asurine = true
			cut_crimsite = true
			cut_limestone = true
			cut_ochrum = true
			cut_scoria = true
			cut_scorchia = true
			cut_veridium = true

		[types.stone_type.create_dd]
			cut_stone = true
			cut_packed_mud = true
			cut_amethyst_block = true
			cut_netherrack = true
			cut_basalt = true
			cut_blackstone = true
			cut_weathered_limestone = true
			cut_gabbro = true
			cut_dolomite = true

		[types.stone_type.tfmg]
			cut_bauxite = true
			cut_galena = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.storagedrawers]
			trim = true
			full_drawers_2 = true
			half_drawers_1 = false
			full_drawers_4 = true
			half_drawers_4 = false
			half_drawers_2 = true
			full_drawers_1 = false

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

