
[Freecam]
	#The type of flight used by freecam.
	#Allowed Values: CREATIVE, DEFAULT
	"Flight Mode" = "DEFAULT"
	#The source of block/entity interactions.
	#Allowed Values: CAMERA, PLAYER
	"Interaction Mode" = "CAMERA"
	#The horizontal speed of freecam.
	#Range: 0.0 ~ 10.0
	"Horizontal Speed" = 1.0
	#The vertical speed of freecam.
	#Range: 0.0 ~ 10.0
	"Vertical Speed" = 1.0
	#Whether you can travel through blocks in freecam.
	"No Clip" = true
	#Disables freecam when damage is received.
	"Disable on Damage" = true
	#Whether you can interact with blocks/entities in freecam.
	#WARNING: Multiplayer usage not advised.
	"Allow Interaction" = false
	#Prevents player movement while freecam is active.
	#WARNING: Multiplayer usage not advised.
	"Freeze Player" = false
	#Shows your player in its original position.
	"Show Player" = true
	#Whether you can see your hand in freecam.
	"Show Hand" = false
	#Notifies you when entering/exiting freecam.
	"Freecam Notifications" = true
	#Notifies you when entering/exiting tripod cameras.
	"Tripod Notifications" = true

